"use client";
import "antd/dist/reset.css";
import "./globals.css";
import type { Metadata } from "next";

import { Provider } from "react-redux";
import { store } from "../store/store";

export const metadata: Metadata = {
  title: "Mark 8",
  description: "Generated by create next app",
};

export default function GlobalHolder({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Provider store={store}>{children}</Provider>;
}
